const COLOR_RED = "#CB1446";
const COLOR_GREEN = "#2AA850";
const COLOR_BLUE = "#2E83F3";
const COLOR_ORANGE = "#FF6700";
const COLOR_FILE_LOAD = "#8cb4fc";
const COLOR_DELETE_FOREVER = "#f23a3a";
const MAIN = document.querySelector("main");
const NAV_TOP = document.querySelector("nav");
const NAV_LEFT = document.querySelector(".nav_left");
const NAV_RIGHT = document.querySelector(".nav_right");
const BLUR_LAYER = document.querySelector(".blur_layer");
const TOTAL_USAGE = document.querySelector("#storage");

let controller;
let multiSelectBucketGL = [];
let isFileMovingGL = false;
let userIdGL = null;
let usageGL = 0;
let secretKeyGL = null;
let trashFilesGL = null;
let openedFolderGL = null;
let openedOptionGL = null;
let taskCountGL = -1;
let taskFactoryGL = {};
var fileContextMenuGL = null;